#!/bin/sh
########################################################################
# Created By: Ross Derewianko
# there's the truth... and the truth.
# Creation Date: July 2017
# Last modified: July 16, 2015
# Brief Description: Checks to see if vpn is newly deployed
########################################################################


#Check to see if Where Is Office exists and spit a result
if [ -f "/Applications/Microsoft Office 2016/Where Is Office.txt" ]; then
	#Check that we're not creating a false positive and check to see if excel exists
	if [ -f "/Applications/Microsoft Excel.app/Contents/MacOS/Microsoft Excel" ]; then
		echo "excel exists"
		echo "<result>no</result>"
		rm -rf "/Applications/Microsoft Office 2016"
	else 
		#Tell Casper office needs to be deployed
		echo "<result>yes</result>"
	fi

else
	#Office does not need to be deployed
	echo "<result>no</result>"

fi
exit 0
