#!/bin/sh
########################################################################
# Created By: Ross Derewianko
# there's the truth... and the truth.
# Creation Date: July 2017
# Last modified: July 16, 2017
# Brief Description: Checks to see if the where is office exists
########################################################################


#Check to see if Where Is Office exists and spit a result
if [[ -f "/Applications/Microsoft Office 2016/Where Is Office.txt" ]]; then
		echo "<result>yes</result>"
else
	#Office does not need to be deployed
	echo "<result>no</result>"

fi
exit 0
