#!/bin/bash
###################################################################################
## Create a folder for Where is office and a txt file
## "Hey man don't have a cow"
## Created: Dec 2017
## Last Edit: July 16, 2017
## Created by Ross Derewianko
###################################################################################


# Determine working directory

install_dir=`dirname $0`


#Move them all into a folder like on 2011
mkdir /Applications/Microsoft\ Office\ 2016
chown root:wheel /Applications/Microsoft\ Office\ 2016
echo "Welcome to your New Mac!" > /Applications/Microsoft\ Office\ 2016/Where\ Is\ Office.txt
echo "To speed up the preparations of your Mac, Microsoft Office 2016 will appear by the end of the day." >> /Applications/Microsoft\ Office\ 2016/Where\ Is\ Office.txt
echo "A popup will appear after Microsoft Office 2016 has been installed." >> /Applications/Microsoft\ Office\ 2016/Where\ Is\ Office.txt




#lets make that folder have a nice icon
python $install_dir"/set-image.py" $install_dir"/Blackvariant-Button-Ui-Ms-Office-2016-Office.png" /Applications/Microsoft\ Office\ 2016/



exit 0
